import Head from 'next/head'
import Main from '../components/Main'
import About from '../components/About'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '../components/Contact'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Andrew | Software Engineer </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/acp-logo.png" />
      </Head>

    <Main/>
    <About/>
    <Skills/>
    <Projects/>
    <Contact/>
    </div>
  )
}
