import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Main from '../components/Main'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Andrew | Software Engineer </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/acp-logo.png" />
      </Head>

    <Navbar/>
    <Main/>
    </div>
  )
}
